[package]
name = "mercek"
version = "0.1.1"
authors = ["Kuuw <zuwu@tuta.io>"]
edition = "2024"
license = "MIT"

[dependencies]
smithay-client-toolkit = "0.21.1"
wayland-client = "0.31.15"
tiny-skia = "0.12.0"
ab_glyph = "0.2.32"
kiddo = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
png = "0.18.1"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
